### ISSUE TITLE
Change Header

### ISSUE THREAD

**Issue by scottsnyder01** [Geneticure/geneticure.com#14]
Change header on the homepage from "Our Team" to "About Us" to align w normal site nomenclature and such...

https://github.com/Geneticure/geneticure.com/blob/33e496b49fde8c641e6048bc3a9009cb1cc2b429/src/pages/team.astro#L11

**Comment by RobertAKARobin** [comment]
It looks like people usually have a 'Company' tab with a 'Team' sub-tab. I don't think we need tabs with sub-tabs — their designs aren't very conducive to D2C.

If we feel the need for a more thorough, punchy "About the company" page then we can build that out. These guys all have them but IMO 3/4 of them are unnecessary:

- https://www.invitae.com/en/about
  - They have a bunch of products, so an overall "company" page makes sense
- https://castlebiosciences.com/company/about-us/
  - Pretty useless page; just some marketing verbiage
- https://www.accessdxlab.com/company/about/
  - Also pretty useless
- https://oneome.com/about/
  - Also pretty useless, except for their team list

Until we have a beefier company page, I'd say stick with 'Team' since (a) it's shorter, and (b) it's already there. We can totally build one, just keep in mind it means taking away time from [something else](https://github.com/orgs/Geneticure/projects/1).

**Comment by RobertAKARobin** [comment]
Never mind, I'm eating my words. :) Here's a first draft of a company tab/page: https://company--geneticure.netlify.app/company/

**Comment by scottsnyder01** [comment]
Looks great

Scott Snyder
952.210.5851
________________________________

**Comment by scottsnyder01** [comment]
I think a Company tab with what we have today is great. Should not ever need a sub tab. We can add new partnerships there and company news unrelated to scientific literature stuff. This is/was our most commonly visited page and I believe on the previous site version was pretty much the team

***@***.***

From: "Robin (Robert) Thomas" ***@***.***>
Reply-To: "Geneticure/geneticure.com" ***@***.***>
Date: Thursday, September 22, 2022 at 10:21 AM
To: "Geneticure/geneticure.com" ***@***.***>
Cc: Scott Snyder ***@***.***>, Author ***@***.***>
Subject: Re: [Geneticure/geneticure.com] Change Header (Issue #14)


It looks like people usually have a 'Company' tab with a 'Team' sub-tab. I don't think we need tabs with sub-tabs — their designs aren't very conducive to D2C.

If we feel the need for a more thorough, punchy "About the company" page then we can build that out. These guys all have them but IMO 3/4 of them are unnecessary:

  *   https://www.invitae.com/en/about
     *   They have a bunch of products, so an overall "company" page makes sense
  *   https://castlebiosciences.com/company/about-us/
     *   Pretty useless page; just some marketing verbiage
  *   https://www.accessdxlab.com/company/about/
     *   Also pretty useless
  *   https://oneome.com/about/
     *   Also pretty useless, except for their team list

Until we have a beefier company page, I'd say stick with 'Team' since (a) it's shorter, and (b) it's already there. We can totally build one, just keep in mind it means taking away time from something else<https://github.com/orgs/Geneticure/projects/1>.
