### ISSUE TITLE
Change all `register` to `activate`

### ISSUE THREAD

**Issue by RobertAKARobin** [Geneticure/geneticure.com#40]
cc @Carl362

**Comment by RobertAKARobin** [comment]
@Carl362 Sorry, forgot to add this to the board. Do we still want this?

**Comment by RobertAKARobin** [comment]
@Carl362 The only places I see the word 'register' on the marketing site are where it's referring to accounts, so the site is correct. We _do_ use `register` in a ton of places in Daryl, however, and that's going to be considerably trickier since a lot of code is dependent on kits having a status of `"registered"`. Is it OK if we kick this can down the road a bit? Since we'll soon be implementing a new version of the algorithm, and there are some other changes I want to make to Daryl, it will probably be easier once things have settled down.

**Comment by scottsnyder01** [comment]
Yep good to kick

From: "Robin (Robert) Thomas" ***@***.***>
Reply-To: "Geneticure/geneticure.com" ***@***.***>
Date: Friday, October 14, 2022 at 1:03 PM
To: "Geneticure/geneticure.com" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Geneticure/geneticure.com] Change all `register` to `activate` (Issue #40)


@Carl362<https://github.com/Carl362> The only places I see the word 'register' on the marketing site are where it's referring to accounts, so the site is correct. We do use register in a ton of places in Daryl, however, and that's going to be considerably trickier since a lot of code is dependent on kits having a status of "registered". Is it OK if we kick this can down the road a bit? Since we'll soon be implementing a new version of the algorithm, and there are some other changes I want to make to Daryl, it will probably be easier once things have settled down.
